add driver specific substring expression building
artemeon/database pull request #14
Opened 2021-04-14 13:00 UTC by MikeMarschall

see artemeon/core-ng#2997

2021-04-14 13:04 UTC, sidler submitted a review, later dismissed

2021-04-14 15:50 UTC, sidler submitted a review, later dismissed

2021-04-14 16:22 UTC, chriskapp approved these changes

2021-04-15 06:54 UTC, sidler requested changes

2021-04-15 06:54 UTC, sidler commented on tests/ConnectionTest.php
> +        $connection->_pQuery(
ggf erst mal ein truncate absetzen? siehe Build fehler

2021-04-15 08:21 UTC, sidler commented on tests/ConnectionTest.php
> +        $connection->_pQuery(
Oder ein Delete from where 1=1, truncate ist afaik nicht auf jeder DB verfügbar

2021-04-15 08:22 UTC, MikeMarschall commented on tests/ConnectionTest.php
> +        $connection->_pQuery(
ich hatte extra vorher geschaut und nicht auf Anhieb gefunden, welche Datenbank das nicht unterstützen würde 😅

2021-04-16 11:32 UTC, sidler approved these changes

2021-04-16 11:43 UTC, chriskapp approved these changes

2021-04-16 11:44 UTC, merged