feat: added Exceptionhandler if tablename isn't found.
artemeon/database pull request #20
Opened 2021-05-11 12:28 UTC by isikbattenstein

#19

2021-05-11 12:31 UTC, isikbattenstein commented on src/Connection.php
>      }
Alternativ könnte man Line 888 auch als condition in 889 packen und bei 893 true returnen, aber ich denke, dass wäre zu viel des guten und würde der Leserlichkeit nicht behilfich sein.

2021-05-11 20:23 UTC, sidler requested changes

2021-05-11 20:23 UTC, sidler commented on tests/ConnectionTest.php
> +            throw new TableNotFoundException('Table not found: ',self::TEST_TABLE_NAME);
warum wirfst du hier eine Exception? ich hätte einfach nur ein 
```suggestion
        $this->expectException(TableNotFoundException::class);
        $connection->hasTable('table_does_not_exist');
```
erwartet

2021-05-12 07:19 UTC, isikbattenstein commented on tests/ConnectionTest.php
> +            throw new TableNotFoundException('Table not found: ',self::TEST_TABLE_NAME);
Ich habe hierzu eben eine Korrektur gepusht. 
Diese Korrektur hatte ich prinzipiell schon gestern gehabt, aber der ist wegen eines Branchwechsel erst in den Stash gewandert. Ich vergaß, diesen anschließend wieder zurück zu holen und zu commiten. 

Demnach ist der Test insofern korrekt, da ich die Exception nicht innerhalb der hasTable Methode werden kann, da sonst alle andern Testcases fehlschlugen, da von den Tests ein Bool erwartet wurde, um eventuell eine Tabelle o.ä. anzulegen, soweit dieser nicht vorhanden ist. Daher musste ich den throw aus der hasTable rausnehmen und um den Methodenaufruf packen, damit die Exception dennoch richtig geworfen wird, aber die testcases dadurch nicht abschmieren.

2021-05-12 07:46 UTC, chriskapp commented on src/Connection.php
> +        $this->hasTable($tableName);
also hier sollten wir dann am besten auch eine `TableNotFoundException` werfen, also wie auch in der `getColumnsOfTable`

2021-05-12 07:46 UTC, chriskapp commented on tests/ConnectionTest.php
> +            throw new TableNotFoundException('Table not found: ',self::TEST_TABLE_NAME);
also die Methode `hasTable` sollte aus meiner Sicht keine Exception werfen sondern nur true oder false zurückgeben. Die Exception würde ich nur bei `getColumnsOfTable` und `getTableInformation` einbauen. Aber ansonsten sieht das mit der `TableNotFoundException` gut aus 👍

2021-05-12 07:52 UTC, isikbattenstein commented on src/Connection.php
> +        $this->hasTable($tableName);
Erledigt und gepush.

2021-05-18 09:54 UTC, isikbattenstein commented on src/Exception/TableNotFoundException.php
> +    public function __construct(string $message, string $table, Throwable $previous = null)
Alles klar. Das passe ich an.

2021-05-18 09:54 UTC, isikbattenstein commented on tests/ConnectionTest.php
> +        if(!$connection->hasTable('table_does_not_exist')) {
Okay, wird dann so umgesetzt.

2021-05-18 15:45 UTC, Beenheed approved these changes

2021-05-18 20:11 UTC, sidler approved these changes

2021-05-19 06:30 UTC, merged