#4323 feat(database): extend EscapeableParameterInterface
artemeon/database pull request #27
Opened 2021-05-21 18:52 UTC by f-kuechler

2021-05-26 08:18 UTC, Beenheed submitted a review, later dismissed

2021-05-26 11:12 UTC, sidler requested changes

2021-05-26 11:12 UTC, sidler commented on src/EscapeableParameterInterface.php
> +    public function getValue(): ?string;
ganz ganz sicher? wir können da ja auch z.B. Date Objekte reingeben, die eine __toString implementiert haben

2021-05-26 11:12 UTC, sidler commented on src/Connection.php
> +            $strString = trim(json_encode($strString), '" ');
(string) cast? was passiert bei Date Objekten?

2021-05-26 11:12 UTC, sidler commented on src/Connection.php
> +            if ($strParam instanceof EscapeableParameterInterface) {
wir brauchen dafür auf jeden Fall unittests

2021-05-26 13:44 UTC, f-kuechler commented on src/EscapeableParameterInterface.php
> +    public function getValue(): ?string;
Hast du eine Beispielstelle dafür ? Eigentlich sollte das nicht möglich sein. 
Das OrmQueryParam Objekt ist aktuell das einzige Objekt, welches dieses Interface implementiert. 
Und dort ist der value Parameter im Constructor als String typisiert. Alles Andere außer String wäre hier aber auch
falsch, da der Parameter in der Connection Klasse überall als String referenziert wird.

2021-05-26 13:47 UTC, f-kuechler commented on src/Connection.php
> +            $strString = trim(json_encode($strString), '" ');
Also wenn die Variable hier "strString" heißt und da dann n Date Object drin ist fände ich das außerordentlich witzig. :D
Erklärung siehe 👉 EscapeableParameterInterface
Zudem passiert das hier auch nur wenn man explizit den Json Flag für den Parameter setzt.

2021-05-26 13:52 UTC, f-kuechler commented on src/Connection.php
> +            if ($strParam instanceof EscapeableParameterInterface) {
Bzw. da gibt es schon Unittests, die das indirekt mit testen sollten. Ich check das aber nochmal.

2021-05-26 17:12 UTC, chriskapp commented on src/Connection.php
> +                $strParam = $this->dbsafeString($strParam->getValue(), true, $strParam->isJsonValue(), $strParam->isJsonValue());
hier wird ja zweimal `isJsonValue` übergeben also auch für `bitAddSlashes`?

2021-05-27 09:48 UTC, f-kuechler commented on src/Connection.php
> +                $strParam = $this->dbsafeString($strParam->getValue(), true, $strParam->isJsonValue(), $strParam->isJsonValue());
Ja, das `AddSlashes` soll ja nur bei Json Values passieren. Also ich wollte zumindest nicht die vorherige Logik ändern. Dort wurde ja explizit da `bitAddSlashes` auf false gesetzt.

2021-05-27 09:49 UTC, f-kuechler commented on src/Connection.php
> +            $strString = trim(json_encode($strString), '" ');
Ok, dann ändere ich mal noch den Variablennamen und füge da ein String Cast hinzu. 👌

2021-05-28 11:04 UTC, f-kuechler commented
Soo, addslashes ist jetzt komplett raus und wurde duch das richtige Escaping aus den Treiber Klassen ersetzt.

2021-05-28 12:39 UTC, chriskapp submitted a review, later dismissed

2021-05-28 14:50 UTC, Beenheed approved these changes

2021-06-04 14:41 UTC, sidler submitted a review, later dismissed

2022-07-29 09:10 UTC, chriskapp commented
Durch den PR https://github.com/artemeon/database/pull/31 bekommen wir dann neue Methoden wo das ganze Escaping nicht mehr gemacht wird, von daher würde ich den PR dann erstmal closen

2022-07-29 09:10 UTC, closed without merging