Feat/#60 handle enums
artemeon/database pull request #61
Opened 2024-02-27 08:09 UTC by chriskapp

2024-02-27 13:38 UTC, sidler submitted a review, later dismissed

2024-02-27 19:33 UTC, marcreichel requested changes

2024-02-27 19:33 UTC, marcreichel commented on CHANGELOG.md
> +## 3.0.1
```suggestion
## 3.2.1
```

We need to add the changelog for the other versions though.

2024-02-28 07:35 UTC, sidler approved these changes

2024-02-28 07:50 UTC, marcreichel approved these changes

2024-02-28 09:54 UTC, merged