Add JsonColumnExpression and slug id separation
artemeon/database pull request #67
Opened 2024-06-12 16:50 UTC by f-kuechler

2024-06-13 15:23 UTC, chriskapp requested changes
Kannst du hier noch einen Test-Case erstellen.

2024-06-13 15:23 UTC, chriskapp commented on src/ConnectionInterface.php
> +    public function getJsonColumnExpression(string $column, string $key): string;
kannst du hier noch einen Test-Case für die beiden Methoden erstellen s. z.B. `tests/ConnectionTest.php:771`, damit wir das gegen alle DBs testen können.

2024-06-14 14:33 UTC, chriskapp commented
FYI @sidler hat hier in einem andere PR https://github.com/artemeon/database/pull/68 den MSSQL Treiber gelöscht, dann müssen wir das für MSSQL auch nicht implementieren, wir sollten den PR dann vorher einfach mergen.

2024-06-17 09:41 UTC, chriskapp approved these changes

2024-06-17 10:43 UTC, sidler approved these changes

2024-06-17 10:48 UTC, merged